#ifndef FLUIDSIM_GLOBALS_HPP_INCLUDED
#define FLUIDSIM_GLOBALS_HPP_INCLUDED

constexpr int NUMCOLUMNS {50}, NUMROWS {25};
constexpr int BOXWIDTH {1000}, BOXHEIGHT {1000};
constexpr float DEFAULTRADIUS {float(BOXWIDTH/NUMCOLUMNS)/2.0};
constexpr int DEFAULTPOINTCOUNT {30};


#endif
